trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - /src/Utilities/*

pool: localhost

stages:
- stage: Building
  jobs:
    - job: Building
      displayName: Motor Pool
      variables:
        rootApiDir : src/Core/MotorPool.API
      steps:
        - task: NuGetToolInstaller@0
          displayName: Install nuget
          inputs:
            versionSpec: 
            checkLatest: true
        - task: UseDotNet@2
          displayName: Install .NET SDK
          inputs:
            packageType: 'sdk'
            version: '8.0.x'
        - task: DotNetCoreCLI@2
          displayName: Restore nuget packages
          inputs:
            command: 'restore'
            projects: 'src/Core/MotorPool.API/MotorPool.API.csproj'
        - task: DotNetCoreCLI@2
          displayName: Build solution
          inputs:
            command: 'build'
            projects: '$(rootApiDir)/MotorPool.API.csproj'
            arguments: '--configuration Release'