version: '3.8'
services:
  motorpool-app:
    build:
      context: .
      dockerfile: ../src/MotorPool.UI/Dockerfile
    ports:
      - "80:5000"
    environment:
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_ENVIRONMENT=Production
      - GraphHopper__ApiKey=${GraphHopper__ApiKey}
    depends_on:
      - motorpool-db
    networks:
      - motorpool-network

  motorpool-db:
    image: alekszakharov/motorpool-db:latest
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - motorpool-network

networks:
  motorpool-network:
    driver: bridge

volumes:
  db-data: